// Sentences and short passages from works whose copyright has long expired
// (all pre-1900 English originals, or a pre-1923 translation), so the text
// this widget hands you is free to paste anywhere: Moby-Dick, Pride and
// Prejudice, Alice's Adventures in Wonderland, A Tale of Two Cities,
// Frankenstein, Walden, The Time Machine, the Sherlock Holmes stories, The
// Wonderful Wizard of Oz, Treasure Island, Dracula, Jane Eyre, Great
// Expectations, Heart of Darkness, Huckleberry Finn, On the Origin of
// Species, and Giles' 1910 translation of The Art of War.
//
// Deliberately mixed in length — a handful of three-word fragments next to
// forty-word Victorian sentences — because an outliner is exactly the kind
// of UI that breaks on both extremes (wrapping, truncation, row height).
export const CORPUS: string[] = [
  'Call me Ishmael.',
  'Whenever I find myself growing grim about the mouth, whenever it is a damp, drizzly November in my soul, then I account it high time to get to sea as soon as I can.',
  'There is nothing surprising in this.',
  'It is a way I have of driving off the spleen and regulating the circulation.',
  'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.',
  'However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered the rightful property of some one or other of their daughters.',
  'My dear Mr. Bennet, have you heard that Netherfield Park is let at last?',
  'You want to tell me, and I have no objection to hearing it.',
  'Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do.',
  'There was nothing so very remarkable in that.',
  'Down, down, down.',
  'Would the fall never come to an end?',
  'It was much pleasanter at home, when one was not always growing larger and smaller.',
  'Who in the world am I?',
  'It was the best of times, it was the worst of times.',
  'It was the age of wisdom, it was the age of foolishness.',
  'It was the epoch of belief, it was the epoch of incredulity.',
  'It was the season of Light, it was the season of Darkness.',
  'You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with such evil forebodings.',
  'There is something at work in my soul which I do not understand.',
  'I am already far north of London, and as I walk in the streets of Petersburgh, I feel a cold northern breeze play upon my cheeks, which braces my nerves and fills me with delight.',
  'I have no friend.',
  'I went to the woods because I wished to live deliberately, to front only the essential facts of life.',
  'The mass of men lead lives of quiet desperation.',
  'Simplicity, simplicity, simplicity.',
  'Time is but the stream I go a-fishing in.',
  'I have travelled a good deal in Concord.',
  'The Time Traveller, for so it will be convenient to speak of him, was expounding a recondite matter to us.',
  'His grey eyes shone and twinkled, and his usually pale face was flushed and animated.',
  'To Sherlock Holmes she is always the woman.',
  'It is a capital mistake to theorise before you have all the evidence.',
  'You see, but you do not observe.',
  'The distinction is clear.',
  'The world is full of obvious things which nobody by any chance ever observes.',
  'It is quite a three pipe problem.',
  'Dorothy lived in the midst of the great Kansas prairies, with Uncle Henry, who was a farmer, and Aunt Em, who was the farmer’s wife.',
  'Their house was small, for the lumber to build it had to be carried by wagon many miles.',
  'There were four walls, a floor and a roof, which made one room.',
  'Toto was not gray; he was a little black dog, with long silky hair and small black eyes that twinkled merrily on either side of his funny, wee nose.',
  'Squire Trelawney, Dr. Livesey, and the rest of these gentlemen having asked me to write down the whole particulars about Treasure Island, I take up my pen in the year of grace 17—.',
  'Fifteen men on the dead man’s chest.',
  'I remember him as if it were yesterday, as he came plodding to the inn door.',
  'Left Munich at 8:35 P.M., arriving at Vienna early next morning.',
  'The impression I had was that we were leaving the West and entering the East.',
  'I was not able to light on any map or work giving the exact locality of the Castle Dracula.',
  'There was no possibility of taking a walk that day.',
  'I am no bird; and no net ensnares me.',
  'The said Eliza, John, and Georgiana were now clustered round their mama in the drawing-room.',
  'My father’s family name being Pirrip, and my Christian name Philip, my infant tongue could make of both names nothing longer or more explicit than Pip.',
  'So, I called myself Pip, and came to be called Pip.',
  'The Nellie, a cruising yawl, swung to her anchor without a flutter of the sails, and was at rest.',
  'The sea-reach of the Thames stretched before us like the beginning of an interminable waterway.',
  'You do not know about me without you have read a book by the name of The Adventures of Tom Sawyer, but that ain’t no matter.',
  'Persons attempting to find a moral in it will be banished.',
  'That is nothing.',
  'When on board H.M.S. Beagle, as naturalist, I was much struck with certain facts in the distribution of the inhabitants of South America.',
  'These facts seemed to me to throw some light on the origin of species.',
  'No one ought to feel surprise at much remaining as yet unexplained.',
  'All warfare is based on deception.',
  'The art of war is of vital importance to the State.',
  'Hence it is a subject of inquiry which can on no account be neglected.',
  'If you know the enemy and know yourself, you need not fear the result of a hundred battles.',
  'In the midst of chaos, there is also opportunity.',
  'Let your plans be dark and impenetrable as night.',
  'Nothing is more difficult, and therefore more precious, than to be able to decide.',
  'It cannot be otherwise.',
];
