export interface Entry {
  word: string;
  /** Best replacement first — the card promotes alts[0] over the rest. */
  alts: string[];
  /**
   * Which sense of an ambiguous headword these alternatives serve. A headword
   * appears twice when "very X" means two unrelated things (a cheap watch and
   * a cheap friend), rather than picking one sense and quietly giving bad
   * advice for the other.
   */
  sense?: string;
}

export const ENTRIES: Entry[] = [
  { word: 'abysmal', alts: ['fathomless', 'bottomless', 'cavernous'] },
  { word: 'accurate', alts: ['exact', 'precise', 'unerring'] },
  { word: 'afraid', alts: ['terrified', 'petrified', 'fearful'] },
  { word: 'aggressive', alts: ['hostile', 'belligerent', 'combative'] },
  { word: 'alive', alts: ['teeming', 'vibrant', 'thriving'] },
  { word: 'amazing', alts: ['astonishing', 'astounding', 'breathtaking'] },
  { word: 'angry', alts: ['furious', 'livid', 'irate', 'incensed'] },
  { word: 'annoyed', alts: ['exasperated', 'indignant', 'irate'] },
  { word: 'annoying', alts: ['exasperating', 'maddening', 'grating'] },
  { word: 'awesome', alts: ['awe-inspiring', 'breathtaking', 'magnificent'] },
  { word: 'awful', alts: ['appalling', 'dreadful', 'atrocious'] },
  { word: 'bad', alts: ['atrocious', 'dreadful', 'abysmal'] },
  { word: 'beautiful', alts: ['exquisite', 'stunning', 'breathtaking'] },
  { word: 'big', alts: ['massive', 'enormous', 'immense'] },
  { word: 'bitter', alts: ['acrimonious', 'rancorous', 'caustic'] },
  { word: 'boring', alts: ['tedious', 'dull', 'mind-numbing'] },
  { word: 'brave', alts: ['fearless', 'valiant', 'intrepid'] },
  { word: 'bright', sense: 'of light', alts: ['dazzling', 'luminous', 'radiant'] },
  { word: 'bright', sense: 'of a person', alts: ['brilliant', 'razor-sharp', 'gifted'] },
  { word: 'busy', sense: 'of a person', alts: ['swamped', 'overloaded', 'snowed under'] },
  { word: 'busy', sense: 'of a place', alts: ['bustling', 'teeming', 'thronged'] },
  { word: 'calm', alts: ['serene', 'tranquil', 'unruffled'] },
  { word: 'careful', alts: ['meticulous', 'painstaking', 'scrupulous'] },
  { word: 'cheap', sense: 'of a price', alts: ['dirt-cheap', 'rock-bottom', 'giveaway'] },
  { word: 'cheap', sense: 'of a person', alts: ['stingy', 'miserly', 'tightfisted'] },
  { word: 'cheerful', alts: ['buoyant', 'jubilant', 'sunny'] },
  { word: 'cheery', alts: ['buoyant', 'chipper', 'sunny'] },
  { word: 'clean', alts: ['spotless', 'immaculate', 'pristine'] },
  { word: 'clear', alts: ['obvious', 'unmistakable', 'unambiguous'] },
  { word: 'clever', alts: ['brilliant', 'ingenious', 'astute'] },
  { word: 'close', sense: 'of distance', alts: ['adjacent', 'neighbouring', 'a stone’s throw away'] },
  { word: 'close', sense: 'of people', alts: ['inseparable', 'intimate', 'devoted'] },
  { word: 'cold', alts: ['freezing', 'frigid', 'bitter'] },
  { word: 'colorful', alts: ['vibrant', 'vivid', 'kaleidoscopic'] },
  { word: 'colourful', alts: ['vibrant', 'vivid', 'kaleidoscopic'] },
  { word: 'common', alts: ['ubiquitous', 'pervasive', 'commonplace'] },
  { word: 'compassionate', alts: ['benevolent', 'tender-hearted', 'humane'] },
  { word: 'competitive', alts: ['cutthroat', 'ferocious', 'dog-eat-dog'] },
  { word: 'complete', alts: ['comprehensive', 'exhaustive', 'total'] },
  { word: 'complicated', alts: ['convoluted', 'byzantine', 'labyrinthine'] },
  { word: 'concerned', alts: ['alarmed', 'anxious', 'distressed'] },
  { word: 'confused', alts: ['bewildered', 'perplexed', 'baffled'] },
  { word: 'confusing', alts: ['bewildering', 'disorienting', 'impenetrable'] },
  { word: 'conventional', alts: ['orthodox', 'conservative', 'staid'] },
  { word: 'cool', alts: ['superb', 'sublime', 'stellar'] },
  { word: 'crazy', alts: ['insane', 'unhinged', 'deranged'] },
  { word: 'creative', alts: ['inventive', 'imaginative', 'ingenious'] },
  { word: 'crowded', alts: ['packed', 'teeming', 'thronged'] },
  { word: 'curious', alts: ['inquisitive', 'agog', 'intrigued'] },
  { word: 'cute', alts: ['adorable', 'endearing', 'precious'] },
  { word: 'dangerous', alts: ['perilous', 'treacherous', 'lethal'] },
  { word: 'dated', alts: ['archaic', 'antiquated', 'obsolete'] },
  { word: 'dear', alts: ['cherished', 'beloved', 'treasured'] },
  { word: 'deep', alts: ['profound', 'bottomless', 'cavernous'] },
  { word: 'depressed', alts: ['despondent', 'desolate', 'inconsolable'] },
  { word: 'detailed', alts: ['meticulous', 'exhaustive', 'granular'] },
  { word: 'determined', alts: ['resolute', 'dogged', 'unwavering'] },
  { word: 'different', alts: ['disparate', 'worlds apart', 'antithetical'] },
  { word: 'difficult', alts: ['arduous', 'gruelling', 'formidable'] },
  { word: 'dirty', alts: ['filthy', 'grimy', 'squalid'] },
  { word: 'disappointed', alts: ['crestfallen', 'disillusioned', 'dismayed'] },
  { word: 'disgusting', alts: ['revolting', 'abominable', 'repugnant'] },
  { word: 'disorganized', alts: ['chaotic', 'shambolic', 'haphazard'] },
  { word: 'distraught', alts: ['inconsolable', 'frantic', 'beside yourself'] },
  { word: 'distrustful', alts: ['suspicious', 'wary', 'cynical'] },
  { word: 'doubtful', alts: ['dubious', 'sceptical', 'improbable'] },
  { word: 'dreary', alts: ['bleak', 'dismal', 'desolate'] },
  { word: 'dry', alts: ['parched', 'arid', 'bone-dry'] },
  { word: 'dull', alts: ['tedious', 'insipid', 'stultifying'] },
  { word: 'dumb', alts: ['dense', 'obtuse', 'idiotic'] },
  { word: 'eager', alts: ['keen', 'avid', 'raring to go'] },
  { word: 'early', alts: ['premature', 'untimely', 'ahead of schedule'] },
  { word: 'easy', alts: ['effortless', 'painless', 'trivial'] },
  { word: 'embarrassed', alts: ['mortified', 'humiliated', 'red-faced'] },
  { word: 'empty', alts: ['desolate', 'barren', 'deserted'] },
  { word: 'enthusiastic', alts: ['fervent', 'exuberant', 'zealous'] },
  { word: 'evil', alts: ['wicked', 'monstrous', 'malevolent'] },
  { word: 'excited', alts: ['thrilled', 'elated', 'exhilarated'] },
  { word: 'exciting', alts: ['exhilarating', 'electrifying', 'gripping'] },
  { word: 'exhausted', alts: ['drained', 'spent', 'depleted'] },
  { word: 'expensive', alts: ['exorbitant', 'extortionate', 'prohibitive'] },
  { word: 'fabulous', alts: ['sublime', 'spectacular', 'phenomenal'] },
  { word: 'fancy', alts: ['lavish', 'opulent', 'ornate'] },
  { word: 'fascinating', alts: ['spellbinding', 'riveting', 'mesmerising'] },
  { word: 'fast', alts: ['rapid', 'blistering', 'breakneck'] },
  { word: 'fat', alts: ['obese', 'corpulent', 'rotund'] },
  { word: 'fatigued', alts: ['exhausted', 'drained', 'spent'] },
  { word: 'fierce', alts: ['ferocious', 'savage', 'feral'] },
  { word: 'focused', alts: ['fixated', 'engrossed', 'single-minded'] },
  { word: 'fortunate', alts: ['providential', 'blessed', 'charmed'] },
  { word: 'friendly', alts: ['amiable', 'affable', 'congenial'] },
  { word: 'frightened', alts: ['terrified', 'petrified', 'panic-stricken'] },
  { word: 'frightening', alts: ['terrifying', 'harrowing', 'hair-raising'] },
  { word: 'full', alts: ['brimming', 'packed', 'crammed'] },
  { word: 'funny', alts: ['hilarious', 'side-splitting', 'uproarious'] },
  { word: 'generous', alts: ['magnanimous', 'open-handed', 'lavish'] },
  { word: 'glad', alts: ['overjoyed', 'delighted', 'elated'] },
  { word: 'good', alts: ['excellent', 'superb', 'first-rate'] },
  { word: 'grateful', alts: ['indebted', 'appreciative', 'beholden'] },
  { word: 'great', alts: ['terrific', 'outstanding', 'magnificent'] },
  { word: 'gross', alts: ['repulsive', 'revolting', 'vile'] },
  { word: 'happy', alts: ['ecstatic', 'elated', 'overjoyed'] },
  { word: 'hard', sense: 'difficult', alts: ['arduous', 'gruelling', 'punishing'] },
  { word: 'hard', sense: 'of a surface', alts: ['rock-hard', 'unyielding', 'adamantine'] },
  { word: 'hard-to-find', alts: ['elusive', 'scarce', 'rare'] },
  { word: 'hard-working', alts: ['diligent', 'industrious', 'tireless'] },
  { word: 'heavy', alts: ['leaden', 'hulking', 'ponderous'] },
  { word: 'high', alts: ['soaring', 'towering', 'lofty'] },
  { word: 'honest', alts: ['candid', 'forthright', 'scrupulous'] },
  { word: 'honored', alts: ['privileged', 'humbled', 'exalted'] },
  { word: 'honoured', alts: ['privileged', 'humbled', 'exalted'] },
  { word: 'hopeful', alts: ['optimistic', 'buoyant', 'sanguine'] },
  { word: 'horny', alts: ['aroused', 'lustful', 'libidinous'] },
  { word: 'hot', alts: ['sweltering', 'scorching', 'blistering'] },
  { word: 'huge', alts: ['colossal', 'gargantuan', 'mammoth'] },
  { word: 'hungry', alts: ['ravenous', 'famished', 'starving'] },
  { word: 'hurt', sense: 'in body', alts: ['battered', 'wounded', 'maimed'] },
  { word: 'hurt', sense: 'in feeling', alts: ['devastated', 'crushed', 'wounded'] },
  { word: 'important', alts: ['crucial', 'vital', 'pivotal'] },
  { word: 'impressive', alts: ['extraordinary', 'formidable', 'awe-inspiring'] },
  { word: 'intelligent', alts: ['brilliant', 'gifted', 'razor-sharp'] },
  { word: 'interesting', alts: ['captivating', 'absorbing', 'compelling'] },
  { word: 'jealous', alts: ['envious', 'covetous', 'possessive'] },
  { word: 'kind', alts: ['compassionate', 'benevolent', 'big-hearted'] },
  { word: 'large', alts: ['vast', 'immense', 'huge'] },
  { word: 'late', alts: ['overdue', 'belated', 'tardy'] },
  { word: 'lazy', alts: ['indolent', 'slothful', 'shiftless'] },
  { word: 'likely', alts: ['probable', 'odds-on', 'all but certain'] },
  { word: 'little', alts: ['tiny', 'minute', 'diminutive'] },
  { word: 'lively', alts: ['animated', 'spirited', 'effervescent'] },
  { word: 'lonely', alts: ['desolate', 'forlorn', 'isolated'] },
  { word: 'long', alts: ['protracted', 'interminable', 'extensive'] },
  { word: 'long-term', alts: ['enduring', 'lasting', 'perennial'] },
  { word: 'loose', alts: ['slack', 'baggy', 'unfastened'] },
  { word: 'loud', alts: ['deafening', 'thunderous', 'ear-splitting'] },
  { word: 'loved', alts: ['adored', 'cherished', 'idolised'] },
  { word: 'lovely', alts: ['enchanting', 'delightful', 'exquisite'] },
  { word: 'mad', sense: 'angry', alts: ['furious', 'livid', 'incensed'] },
  { word: 'mad', sense: 'insane', alts: ['deranged', 'unhinged', 'delirious'] },
  { word: 'mean', alts: ['cruel', 'vicious', 'malicious'] },
  { word: 'messy', alts: ['slovenly', 'squalid', 'chaotic'] },
  { word: 'neat', alts: ['immaculate', 'pristine', 'spick-and-span'] },
  { word: 'necessary', alts: ['essential', 'indispensable', 'vital'] },
  { word: 'nervous', alts: ['apprehensive', 'jittery', 'on edge'] },
  { word: 'new', alts: ['brand-new', 'novel', 'unprecedented'] },
  { word: 'nice', alts: ['delightful', 'charming', 'kind-hearted'] },
  { word: 'noisy', alts: ['deafening', 'raucous', 'clamorous'] },
  { word: 'normal', alts: ['unremarkable', 'mundane', 'run-of-the-mill'] },
  { word: 'obvious', alts: ['glaring', 'self-evident', 'unmistakable'] },
  { word: 'often', alts: ['constantly', 'incessantly', 'relentlessly'] },
  { word: 'old', alts: ['ancient', 'age-old', 'decrepit'] },
  { word: 'old-fashioned', alts: ['archaic', 'antiquated', 'quaint'] },
  { word: 'open', alts: ['candid', 'frank', 'forthright'] },
  { word: 'painful', alts: ['excruciating', 'agonising', 'searing'] },
  { word: 'pale', alts: ['ashen', 'pallid', 'wan'] },
  { word: 'perfect', alts: ['flawless', 'impeccable', 'immaculate'] },
  { word: 'pleased', alts: ['delighted', 'thrilled', 'gratified'] },
  { word: 'polite', alts: ['courteous', 'gracious', 'deferential'] },
  { word: 'poor', alts: ['destitute', 'impoverished', 'penniless'] },
  { word: 'popular', alts: ['ubiquitous', 'beloved', 'all the rage'] },
  { word: 'powerful', alts: ['formidable', 'mighty', 'overwhelming'] },
  { word: 'precise', alts: ['meticulous', 'exacting', 'pinpoint'] },
  { word: 'pretty', alts: ['gorgeous', 'stunning', 'ravishing'] },
  { word: 'pumped', alts: ['fired up', 'exhilarated', 'raring to go'] },
  { word: 'quick', alts: ['rapid', 'lightning-fast', 'instantaneous'] },
  { word: 'quiet', alts: ['hushed', 'silent', 'muted'] },
  { word: 'rainy', alts: ['torrential', 'pouring', 'teeming'] },
  { word: 'rare', alts: ['scarce', 'exceptional', 'one of a kind'] },
  { word: 'relaxed', alts: ['serene', 'laid-back', 'unruffled'] },
  { word: 'rich', alts: ['wealthy', 'affluent', 'loaded'] },
  { word: 'risky', alts: ['perilous', 'precarious', 'hazardous'] },
  { word: 'roomy', alts: ['spacious', 'capacious', 'cavernous'] },
  { word: 'rude', alts: ['insolent', 'obnoxious', 'boorish'] },
  { word: 'runny', alts: ['watery', 'diluted', 'thin'] },
  { word: 'sad', alts: ['sorrowful', 'heartbroken', 'despondent'] },
  { word: 'safe', alts: ['secure', 'impregnable', 'foolproof'] },
  { word: 'scared', alts: ['petrified', 'terrified', 'panic-stricken'] },
  { word: 'scary', alts: ['chilling', 'terrifying', 'spine-chilling'] },
  { word: 'serious', alts: ['grave', 'solemn', 'grievous'] },
  { word: 'sexy', alts: ['seductive', 'alluring', 'ravishing'] },
  { word: 'sharp', alts: ['razor-sharp', 'keen', 'honed'] },
  { word: 'shiny', alts: ['gleaming', 'glistening', 'lustrous'] },
  { word: 'shocked', alts: ['stunned', 'aghast', 'thunderstruck'] },
  { word: 'short', sense: 'of time', alts: ['brief', 'fleeting', 'momentary'] },
  { word: 'short', sense: 'of height', alts: ['diminutive', 'pint-sized', 'stubby'] },
  { word: 'shy', alts: ['timid', 'bashful', 'retiring'] },
  { word: 'sick', alts: ['gravely ill', 'ailing', 'stricken'] },
  { word: 'silly', alts: ['ridiculous', 'absurd', 'preposterous'] },
  { word: 'simple', alts: ['elementary', 'rudimentary', 'effortless'] },
  { word: 'skinny', alts: ['skeletal', 'emaciated', 'gaunt'] },
  { word: 'sleepy', alts: ['drowsy', 'somnolent', 'lethargic'] },
  { word: 'slow', alts: ['sluggish', 'glacial', 'plodding'] },
  { word: 'small', alts: ['tiny', 'minuscule', 'petite'] },
  { word: 'smart', alts: ['brilliant', 'astute', 'razor-sharp'] },
  { word: 'smelly', alts: ['pungent', 'rank', 'fetid'] },
  { word: 'smooth', alts: ['sleek', 'glassy', 'silken'] },
  { word: 'soft', alts: ['downy', 'plush', 'velvety'] },
  { word: 'sorry', alts: ['remorseful', 'contrite', 'apologetic'] },
  { word: 'spacey', alts: ['dazed', 'vacant', 'scatterbrained'] },
  { word: 'spacious', alts: ['cavernous', 'sprawling', 'boundless'] },
  { word: 'spacy', alts: ['dazed', 'vacant', 'scatterbrained'] },
  { word: 'special', alts: ['exceptional', 'singular', 'extraordinary'] },
  { word: 'specific', alts: ['precise', 'explicit', 'definite'] },
  { word: 'strange', alts: ['bizarre', 'uncanny', 'surreal'] },
  { word: 'stressed', alts: ['frazzled', 'overwhelmed', 'burnt out'] },
  { word: 'strict', alts: ['stringent', 'draconian', 'uncompromising'] },
  { word: 'strong', alts: ['powerful', 'formidable', 'herculean'] },
  { word: 'stupid', alts: ['idiotic', 'moronic', 'asinine'] },
  { word: 'successful', alts: ['prosperous', 'thriving', 'flourishing'] },
  { word: 'sudden', alts: ['abrupt', 'instantaneous', 'out of nowhere'] },
  { word: 'superb', alts: ['sublime', 'magnificent', 'peerless'] },
  { word: 'sure', alts: ['certain', 'positive', 'convinced'] },
  { word: 'surprised', alts: ['astonished', 'astounded', 'dumbfounded'] },
  { word: 'suspicious', alts: ['wary', 'mistrustful', 'leery'] },
  { word: 'sweet', sense: 'of a person', alts: ['thoughtful', 'tender-hearted', 'endearing'] },
  { word: 'sweet', sense: 'of a taste', alts: ['sugary', 'cloying', 'syrupy'] },
  { word: 'talented', alts: ['gifted', 'virtuosic', 'prodigious'] },
  { word: 'talkative', alts: ['garrulous', 'loquacious', 'voluble'] },
  { word: 'tall', alts: ['towering', 'statuesque', 'lofty'] },
  { word: 'tasty', alts: ['delicious', 'delectable', 'mouth-watering'] },
  { word: 'terrible', alts: ['horrendous', 'appalling', 'catastrophic'] },
  { word: 'thin', alts: ['slender', 'willowy', 'wafer-thin'] },
  { word: 'thirsty', alts: ['parched', 'dehydrated', 'gasping'] },
  { word: 'tight', alts: ['constricting', 'skintight', 'vice-like'] },
  { word: 'tiny', alts: ['minuscule', 'microscopic', 'infinitesimal'] },
  { word: 'tired', alts: ['exhausted', 'drained', 'worn out'] },
  { word: 'ugly', alts: ['hideous', 'grotesque', 'repulsive'] },
  { word: 'unfortunate', alts: ['regrettable', 'lamentable', 'calamitous'] },
  { word: 'unhappy', alts: ['miserable', 'wretched', 'despondent'] },
  { word: 'unlikely', alts: ['improbable', 'far-fetched', 'remote'] },
  { word: 'upset', alts: ['distraught', 'devastated', 'inconsolable'] },
  { word: 'useful', alts: ['invaluable', 'indispensable', 'advantageous'] },
  { word: 'valuable', alts: ['priceless', 'invaluable', 'precious'] },
  { word: 'warm', alts: ['sweltering', 'stifling', 'sultry'] },
  { word: 'wary', alts: ['vigilant', 'guarded', 'circumspect'] },
  { word: 'weak', alts: ['frail', 'feeble', 'debilitated'] },
  { word: 'weary', alts: ['exhausted', 'worn out', 'bone-tired'] },
  { word: 'weird', alts: ['bizarre', 'surreal', 'outlandish'] },
  { word: 'well-to-do', alts: ['wealthy', 'affluent', 'moneyed'] },
  { word: 'wet', alts: ['soaked', 'drenched', 'sodden'] },
  { word: 'wicked', alts: ['villainous', 'malevolent', 'diabolical'] },
  { word: 'wide', alts: ['expansive', 'sprawling', 'vast'] },
  { word: 'willing', alts: ['eager', 'keen', 'game'] },
  { word: 'windy', alts: ['blustery', 'gale-force', 'howling'] },
  { word: 'wise', alts: ['sagacious', 'sage', 'judicious'] },
  { word: 'worried', alts: ['anxious', 'fretful', 'distressed'] },
];

/**
 * Everything that can stand where "very" stands. A person reaching for this
 * widget is as likely to have written "really tired" or "so tired" as the
 * canonical form, and the advice is identical, so all of them are stripped
 * before lookup rather than only the one in the widget's name.
 */
export const INTENSIFIERS = [
  'very',
  'really',
  'so',
  'extremely',
  'super',
  'quite',
  'totally',
  'incredibly',
  'awfully',
  'terribly',
  'highly',
  'seriously',
  'insanely',
  'ridiculously',
  'absolutely',
  'utterly',
  'pretty',
  'rather',
  'mega',
  'well',
  'dead',
  'hella',
];
